#!/usr/local/bin/ruby -I ./lib/

# == Synopsis 
#   This command computes arrays of relatively prime integers
#
# == Examples
#   This command computes arrays of relatively prime integers
#     array_generator numbers.txt
#
#   Other examples:
#     array_generator -q numbers.txt
#     array_generator --verbose numbers.txt
USAGE = <<-EOS
== Usage 
  array_generator [options] source_file

  For help use: find_normal -h

== Options
  -h, --help          Displays help message
  -v, --version       Display the version, then exit
  -q, --quiet         Output as little as possible, overrides verbose
  -V, --verbose       Verbose output
  -X, --very-verbose Very verbose output

== Author
  Ashley Shimabuku, Jeff Remer

== Copyright
  Copyright (c) 2011 Ashley Shimabuku, Jeff Remer. Licensed under the MIT License:
  http://www.opensource.org/licenses/mit-license.php
EOS

require 'optparse'
require 'ostruct'
require 'date'
require 'array'
require 'yaml'


class App
  VERSION = '0.0.1'
  
  attr_reader :options

  def initialize(arguments, stdin)
    @arguments = arguments
    @stdin = stdin
    
    @output_dir = generate_output_dir_name
    @error_file = "output/error_#{Time.now.to_i}.log"
    Dir.mkdir("output") unless Dir.exists?("output")
    
    # Set defaults
    @options = OpenStruct.new
    @options.verbose = false
    @options.very_verbose = false
    @options.quiet = false
  end

  # Parse options, check arguments, then process the command
  def run
        
    if parsed_options? && arguments_valid? 
      
      puts "Start at #{DateTime.now}\n\n" if @options.verbose
      
      output_options if @options.verbose
            
      process_arguments            
      process_command
      
      puts "\nFinished at #{DateTime.now}" if @options.verbose
      
    else
      output_usage
    end
      
  end
  
  protected
  
    def parsed_options?
      
      # Specify options
      opts = OptionParser.new 
      opts.on('-v', '--version')          { output_version ; exit 0 }
      opts.on('-h', '--help')             { output_help }
      opts.on('-V', '--verbose')          { @options.verbose = true } 
      opts.on('-X', '--very-verbose')     { @options.very_verbose = true }   
      opts.on('-q', '--quiet')            { @options.quiet = true }
            
      opts.parse!(@arguments) rescue return false
      
      process_options
      true      
    end

    # Performs post-parse processing on options
    def process_options
      @options.verbose = false if @options.quiet
      @options.very_verbose = false if @options.quiet
      @options.verbose = true if @options.very_verbose
    end
    
    def output_options
      puts "Options:\n"
      
      @options.marshal_dump.each do |name, val|        
        puts "  #{name} = #{val}"
      end
    end

    # True if required arguments were provided
    def arguments_valid?
      true if @arguments.length == 1 && File.exists?(@arguments.first)
    end
    
    # Setup the arguments
    def process_arguments
      @input_filename = @arguments.first
    end
    
    def output_help
      output_version
      puts USAGE
      exit
    end
    
    def output_usage
      puts USAGE
      exit
    end
    
    def output_version
      puts "#{File.basename(__FILE__)} version #{VERSION}"
    end
    
    def process_command
      $VERBOSE=nil
      line_count = `wc -l < #{@input_filename}`.chomp.strip.to_i
      processed_count = 0
      puts "\nProcessing #{@input_filename}: #{line_count} total lines\n\n" if @options.verbose
      IO.foreach(@input_filename){ |line|
        begin
          process_line(line)
        rescue
          log_error(line)
        end
        processed_count += 1
        percent_done = sprintf "%.2f", (processed_count / line_count.to_f) * 100
        puts "Processed #{processed_count} of #{line_count} (#{line.chomp}) (#{percent_done}%)" if @options.verbose
      }
    end
    
    def process_line(line)      
      array_length = line(0)
      lower_bound = line(1)
      upper_bound = line(2)
      
      
      
      
    end  
      
      
end

# Create and run the application
app = App.new(ARGV, STDIN)
app.run
