# This file was *autogenerated* from the file genericpt.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_4 = Integer(4)
M44 = MatrixSpace(QQ,_sage_const_4 ,_sage_const_4 ); A = M44([%s]); V4 = VectorSpace(QQ,_sage_const_4 ); b = V4([]); octave.solve_linear_system(A,b); 
M44 = MatrixSpace(QQ,_sage_const_4 ,_sage_const_4 ); A = M44([%s]); V4 = VectorSpace(QQ,_sage_const_4 ); b = V4([]); octave.solve_linear_system(A,b); 
M44 = MatrixSpace(QQ,_sage_const_4 ,_sage_const_4 ); A = M44([%s]); V4 = VectorSpace(QQ,_sage_const_4 ); b = V4([]); octave.solve_linear_system(A,b); 
