# This file was *autogenerated* from the file matrix.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_4 = Integer(4)
M = MatrixSpace(QQ,_sage_const_4 ,_sage_const_4 ); A = M([]); print det(A);
