#!/usr/bin/perl 
# Finds list of five numbers from 1 to 30 that are relatively prime.

use Math::BigInt;

sub gcd { # find gcd of a list
	Math::BigInt::bgcd(@_);
}


for($x=1; $x < 50; $x++) { # count from 1 to 50
	for($y=$x+1; $y < 50; $y++) { # count from 1 to 50
		for($z=$y+1; $z < 50; $z++) { # count from 1 to 50
			for($j=$z+1; $j <= 50; $j++) { # count from 1 to 50
				for($i=$j+1; $i <= 50; $i++) { # count from 1 to 50
					if(&gcd($x,$y,$z,$j,$i)==1) {
						print "$x,$y,$z,$j,$i\n";
					}
				}
			}
		}
	}
}